import test,{before,after} from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import { mkdtemp,rm } from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
const temp=await mkdtemp(path.join(os.tmpdir(),'softify-test-'));process.env.DATA_FILE=path.join(temp,'db.json');
const [{app},{initStore}]=await Promise.all([import('../src/app.js'),import('../src/store.js')]);let server,base,token;
async function request(route,options={}){const r=await fetch(base+route,{...options,headers:{...(options.body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:`Bearer ${token}`}:{})}});const type=r.headers.get('content-type')||'';if(r.status===204)return {status:r.status,data:null};return {status:r.status,data:type.includes('json')?await r.json():await r.text()}}
before(async()=>{await initStore(true);server=http.createServer(app);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));base=`http://127.0.0.1:${server.address().port}`});after(async()=>{await new Promise(resolve=>server.close(resolve));await rm(temp,{recursive:true,force:true})});
test('health endpoint is public',async()=>{const r=await request('/api/health');assert.equal(r.status,200);assert.equal(r.data.status,'ok')});
test('protected endpoint rejects anonymous request',async()=>{const r=await request('/api/dashboard');assert.equal(r.status,401)});
test('login and dashboard work',async()=>{const r=await request('/api/auth/login',{method:'POST',body:JSON.stringify({email:'admin@softify.local',password:'Admin@123'})});assert.equal(r.status,200);token=r.data.token;const d=await request('/api/dashboard');assert.equal(d.status,200);assert.ok(d.data.kpis.projects>=3)});
test('CRUD lifecycle works',async()=>{const create=await request('/api/requirements',{method:'POST',body:JSON.stringify({projectId:'PRJ-COMMERCE',title:'Test requirement',type:'Functional',status:'Draft',priority:'Medium'})});assert.equal(create.status,201);const id=create.data.item.id;const update=await request(`/api/requirements/${id}`,{method:'PATCH',body:JSON.stringify({status:'Approved'})});assert.equal(update.data.item.status,'Approved');const del=await request(`/api/requirements/${id}`,{method:'DELETE'});assert.equal(del.status,204)});
test('traceability, AI and reports work',async()=>{assert.equal((await request('/api/traceability')).status,200);const ai=await request('/api/ai/generate-tests',{method:'POST',body:JSON.stringify({requirement:'User can sign in.'})});assert.equal(ai.status,200);assert.equal(ai.data.generated.length,8);assert.equal((await request('/api/reports/summary')).status,200);const csv=await request('/api/reports/export?collection=defects');assert.equal(csv.status,200);assert.match(csv.data,/BUG-COM-417/)});
