import { hashPassword } from './security.js';

const D = (day, time='09:00:00') => `2026-08-${String(day).padStart(2,'0')}T${time}.000Z`;
export function buildSeed() {
  return {
    meta: { version: 2, seededAt: D(22,'08:00:00'), updatedAt: D(22,'08:00:00') },
    organizations: [{ id:'ORG-001', name:'Softify Labs', slug:'softify-labs', plan:'Enterprise Trial', status:'Active', createdAt:D(1), updatedAt:D(22) }],
    users: [
      { id:'USR-ADMIN', organizationId:'ORG-001', name:'Alex Morgan', email:'admin@softify.local', passwordHash:hashPassword('Admin@123'), role:'Organization Admin', status:'Active', title:'Quality Director', createdAt:D(1), updatedAt:D(22) },
      { id:'USR-QA', organizationId:'ORG-001', name:'Priya Sharma', email:'qa@softify.local', passwordHash:hashPassword('Quality@123'), role:'QA Engineer', status:'Active', title:'Senior QA Engineer', createdAt:D(2), updatedAt:D(21) },
      { id:'USR-DEV', organizationId:'ORG-001', name:'Daniel Kim', email:'dev@softify.local', passwordHash:hashPassword('Develop@123'), role:'Developer', status:'Active', title:'Lead Developer', createdAt:D(2), updatedAt:D(20) },
      { id:'USR-SEC', organizationId:'ORG-001', name:'Maya Chen', email:'security@softify.local', passwordHash:hashPassword('Security@123'), role:'Security Engineer', status:'Active', title:'AppSec Engineer', createdAt:D(2), updatedAt:D(22) }
    ],
    projects: [
      { id:'PRJ-COMMERCE', organizationId:'ORG-001', key:'COM', name:'Commerce Cloud', description:'Modern B2C commerce platform across web, API and mobile.', methodology:'Agile / Scrum', lifecycle:'DevSecOps', status:'Active', health:'At Risk', ownerId:'USR-ADMIN', startDate:'2026-06-01', targetDate:'2026-09-15', progress:68, createdAt:D(3), updatedAt:D(22) },
      { id:'PRJ-ERP', organizationId:'ORG-001', key:'ERP', name:'Finance ERP Modernization', description:'Migration and validation of enterprise finance workflows.', methodology:'V-Model', lifecycle:'SDLC', status:'Active', health:'On Track', ownerId:'USR-QA', startDate:'2026-05-15', targetDate:'2026-10-30', progress:54, createdAt:D(3), updatedAt:D(21) },
      { id:'PRJ-MOBILE', organizationId:'ORG-001', key:'MOB', name:'Customer Mobile App', description:'iOS and Android customer application.', methodology:'Kanban', lifecycle:'DevOps', status:'Planning', health:'On Track', ownerId:'USR-QA', startDate:'2026-08-10', targetDate:'2026-12-10', progress:18, createdAt:D(10), updatedAt:D(20) }
    ],
    requirements: [
      { id:'REQ-COM-101', projectId:'PRJ-COMMERCE', type:'Functional', title:'Guest checkout', description:'Customers can complete checkout without creating an account.', acceptanceCriteria:['Guest can add products and pay','Order confirmation is generated','Guest email receives receipt'], priority:'Critical', status:'Approved', ownerId:'USR-QA', version:2, risk:'High', tags:['checkout','revenue'], createdAt:D(5), updatedAt:D(20) },
      { id:'REQ-COM-102', projectId:'PRJ-COMMERCE', type:'Non-Functional', title:'Checkout performance', description:'P95 checkout API response must remain below 800 ms at 500 concurrent users.', acceptanceCriteria:['P95 < 800ms','Error rate < 1%','500 concurrent users'], priority:'High', status:'Approved', ownerId:'USR-DEV', version:1, risk:'High', tags:['performance','api'], createdAt:D(6), updatedAt:D(18) },
      { id:'REQ-COM-103', projectId:'PRJ-COMMERCE', type:'Security', title:'Payment data protection', description:'Payment workflows must not persist raw card data and must enforce strong transport security.', acceptanceCriteria:['No PAN in logs','TLS enforced','Tokens used for payment references'], priority:'Critical', status:'In Review', ownerId:'USR-SEC', version:3, risk:'Critical', tags:['security','payments'], createdAt:D(6), updatedAt:D(22) },
      { id:'REQ-ERP-201', projectId:'PRJ-ERP', type:'Business', title:'Dual approval for journal entries', description:'Journal entries above the threshold require maker-checker approval.', acceptanceCriteria:['Initiator cannot approve own entry','Audit trail captures decisions'], priority:'High', status:'Approved', ownerId:'USR-QA', version:1, risk:'High', tags:['finance','approval'], createdAt:D(4), updatedAt:D(17) },
      { id:'REQ-MOB-301', projectId:'PRJ-MOBILE', type:'Functional', title:'Biometric login', description:'Users can enable Face ID or fingerprint authentication.', acceptanceCriteria:['Opt-in required','Fallback to secure credential','Lockout policy applies'], priority:'Medium', status:'Draft', ownerId:'USR-QA', version:1, risk:'Medium', tags:['mobile','authentication'], createdAt:D(12), updatedAt:D(20) }
    ],
    assets: [
      { id:'AST-WEB-001', projectId:'PRJ-COMMERCE', title:'Commerce Storefront', type:'Website', url:'https://example.com/', environment:'Staging', ownerId:'USR-QA', status:'In Testing', priority:'Critical', focus:['QA','QC','Functional','Security','Accessibility'], tags:['web','checkout'], description:'Responsive B2C storefront and checkout experience.', createdAt:D(8), updatedAt:D(22) },
      { id:'AST-API-001', projectId:'PRJ-COMMERCE', title:'Orders REST API', type:'API', url:'https://example.com/api/orders', environment:'Staging', ownerId:'USR-DEV', status:'Failed', priority:'High', focus:['Functional','Security','Performance'], tags:['api','orders'], description:'Order creation, status, authorization and error handling.', createdAt:D(8), updatedAt:D(22) },
      { id:'AST-ERP-001', projectId:'PRJ-ERP', title:'Finance ERP Client', type:'Enterprise Software', url:'', environment:'UAT', ownerId:'USR-QA', status:'Passed', priority:'Critical', focus:['QA','QC','Functional','Security'], tags:['erp','finance'], description:'Enterprise desktop and browser finance workflows.', createdAt:D(7), updatedAt:D(21) },
      { id:'AST-MOB-001', projectId:'PRJ-MOBILE', title:'Customer Android App', type:'Mobile App', url:'', environment:'QA', ownerId:'USR-QA', status:'Ready', priority:'High', focus:['Functional','Security','Compatibility','Usability'], tags:['android','mobile'], description:'Android application build 0.8.2.', createdAt:D(14), updatedAt:D(20) },
      { id:'AST-VID-001', projectId:'PRJ-COMMERCE', title:'Checkout Demo Video', type:'Video', url:'https://www.youtube.com/', environment:'Content QA', ownerId:'USR-QA', status:'Ready', priority:'Low', focus:['QC','Accessibility','Compatibility'], tags:['video','captions'], description:'Product demo requiring media and caption checks.', createdAt:D(13), updatedAt:D(19) }
    ],
    testPlans: [
      { id:'TPL-COM-R12', projectId:'PRJ-COMMERCE', name:'Release 1.2 Test Plan', scope:'Checkout, catalog, payment, orders and regression.', strategy:'Risk-based functional, API, security, performance and accessibility testing.', entryCriteria:'Build deployed; critical requirements approved.', exitCriteria:'95% pass; no open critical defects; security gate passed.', status:'Active', ownerId:'USR-QA', startDate:'2026-08-15', endDate:'2026-08-29', createdAt:D(15), updatedAt:D(22) },
      { id:'TPL-ERP-UAT1', projectId:'PRJ-ERP', name:'ERP UAT Cycle 1', scope:'Journal entry, approvals and audit trail.', strategy:'Business-process and data-integrity validation.', entryCriteria:'Migrated test data approved.', exitCriteria:'Business sign-off and zero blocker defects.', status:'Active', ownerId:'USR-QA', startDate:'2026-08-18', endDate:'2026-09-05', createdAt:D(16), updatedAt:D(21) }
    ],
    testCases: [
      { id:'TC-COM-001', projectId:'PRJ-COMMERCE', planId:'TPL-COM-R12', requirementIds:['REQ-COM-101'], title:'Complete valid guest checkout', type:'End-to-End', priority:'Critical', automationStatus:'Automated', preconditions:'Product in stock; test payment configured.', steps:['Open product','Add to cart','Checkout as guest','Enter valid details','Submit payment'], expectedResult:'Order is created and confirmation is displayed.', status:'Ready', ownerId:'USR-QA', tags:['smoke','checkout'], createdAt:D(15), updatedAt:D(21) },
      { id:'TC-COM-002', projectId:'PRJ-COMMERCE', planId:'TPL-COM-R12', requirementIds:['REQ-COM-101','REQ-COM-103'], title:'Reject malicious checkout input', type:'Security', priority:'High', automationStatus:'Automated', preconditions:'Staging environment available.', steps:['Submit XSS payload','Submit SQL metacharacters','Inspect response and logs'], expectedResult:'Input is safely rejected; no execution or data leakage occurs.', status:'Ready', ownerId:'USR-SEC', tags:['security','negative'], createdAt:D(16), updatedAt:D(22) },
      { id:'TC-COM-003', projectId:'PRJ-COMMERCE', planId:'TPL-COM-R12', requirementIds:['REQ-COM-102'], title:'Checkout API load at 500 users', type:'Performance', priority:'High', automationStatus:'Automated', preconditions:'Performance environment and dataset ready.', steps:['Ramp to 500 users','Hold for 20 minutes','Collect percentile metrics'], expectedResult:'P95 below 800ms and errors below 1%.', status:'Ready', ownerId:'USR-DEV', tags:['k6','performance'], createdAt:D(17), updatedAt:D(21) },
      { id:'TC-ERP-001', projectId:'PRJ-ERP', planId:'TPL-ERP-UAT1', requirementIds:['REQ-ERP-201'], title:'Enforce dual approval threshold', type:'Functional', priority:'Critical', automationStatus:'Manual', preconditions:'Maker and checker users exist.', steps:['Create high-value journal','Attempt self approval','Approve as checker'], expectedResult:'Self approval blocked; checker approval recorded.', status:'Ready', ownerId:'USR-QA', tags:['uat','approval'], createdAt:D(18), updatedAt:D(20) },
      { id:'TC-MOB-001', projectId:'PRJ-MOBILE', planId:'', requirementIds:['REQ-MOB-301'], title:'Biometric login fallback', type:'Mobile', priority:'Medium', automationStatus:'Planned', preconditions:'Biometric-enabled device.', steps:['Enable biometrics','Fail biometric scan','Use credential fallback'], expectedResult:'Secure fallback succeeds and event is audited.', status:'Draft', ownerId:'USR-QA', tags:['mobile','auth'], createdAt:D(19), updatedAt:D(20) }
    ],
    testRuns: [
      { id:'RUN-COM-0822', projectId:'PRJ-COMMERCE', planId:'TPL-COM-R12', name:'Release 1.2 Regression — Aug 22', environment:'Staging', build:'1.2.0-rc.4', status:'In Progress', total:128, passed:94, failed:12, blocked:4, notExecuted:18, startedAt:D(22,'07:30:00'), completedAt:'', ownerId:'USR-QA', createdAt:D(22,'07:30:00'), updatedAt:D(22,'12:00:00') },
      { id:'RUN-ERP-0821', projectId:'PRJ-ERP', planId:'TPL-ERP-UAT1', name:'ERP UAT Smoke — Aug 21', environment:'UAT', build:'2026.08.21.3', status:'Completed', total:42, passed:39, failed:2, blocked:1, notExecuted:0, startedAt:D(21,'08:00:00'), completedAt:D(21,'12:10:00'), ownerId:'USR-QA', createdAt:D(21,'08:00:00'), updatedAt:D(21,'12:10:00') }
    ],
    defects: [
      { id:'BUG-COM-417', projectId:'PRJ-COMMERCE', requirementIds:['REQ-COM-101'], testCaseId:'TC-COM-001', title:'Duplicate order created on payment retry', description:'Rapid retry after gateway timeout creates two orders.', severity:'Critical', priority:'Critical', status:'In Progress', environment:'Staging', build:'1.2.0-rc.4', assigneeId:'USR-DEV', reporterId:'USR-QA', rootCause:'Pending analysis', createdAt:D(22,'08:20:00'), updatedAt:D(22,'12:15:00') },
      { id:'BUG-COM-411', projectId:'PRJ-COMMERCE', requirementIds:['REQ-COM-102'], testCaseId:'TC-COM-003', title:'P95 checkout latency exceeds target', description:'P95 reaches 1.24s at 500 concurrent users.', severity:'High', priority:'High', status:'Ready for Retest', environment:'Performance', build:'1.2.0-rc.3', assigneeId:'USR-DEV', reporterId:'USR-QA', rootCause:'Unindexed promotion lookup', createdAt:D(20), updatedAt:D(22) },
      { id:'BUG-COM-398', projectId:'PRJ-COMMERCE', requirementIds:['REQ-COM-101'], testCaseId:'TC-COM-001', title:'Keyboard focus hidden in payment modal', description:'Focus indicator is not visible on card fields.', severity:'Medium', priority:'Medium', status:'Fixed', environment:'Staging', build:'1.2.0-rc.2', assigneeId:'USR-DEV', reporterId:'USR-QA', rootCause:'CSS outline reset', createdAt:D(18), updatedAt:D(21) },
      { id:'BUG-ERP-112', projectId:'PRJ-ERP', requirementIds:['REQ-ERP-201'], testCaseId:'TC-ERP-001', title:'Audit export omits rejection comment', description:'CSV export does not include rejection rationale.', severity:'Medium', priority:'High', status:'Assigned', environment:'UAT', build:'2026.08.21.3', assigneeId:'USR-DEV', reporterId:'USR-QA', rootCause:'', createdAt:D(21), updatedAt:D(22) }
    ],
    vulnerabilities: [
      { id:'VULN-COM-071', projectId:'PRJ-COMMERCE', assetId:'AST-WEB-001', title:'Outdated client-side dependency', category:'SCA', cwe:'CWE-1104', cvss:8.1, severity:'High', status:'Remediation', ownerId:'USR-DEV', dueDate:'2026-08-28', evidence:'Detected by dependency scan in release pipeline.', remediation:'Upgrade dependency and rerun SCA + regression.', createdAt:D(20), updatedAt:D(22) },
      { id:'VULN-COM-068', projectId:'PRJ-COMMERCE', assetId:'AST-API-001', title:'Missing rate limit on guest order lookup', category:'DAST', cwe:'CWE-770', cvss:7.5, severity:'High', status:'Open', ownerId:'USR-SEC', dueDate:'2026-08-26', evidence:'Repeated requests accepted without throttling.', remediation:'Apply gateway quota and abuse detection.', createdAt:D(19), updatedAt:D(22) },
      { id:'VULN-ERP-022', projectId:'PRJ-ERP', assetId:'AST-ERP-001', title:'Verbose database error in UAT log', category:'SAST', cwe:'CWE-209', cvss:4.3, severity:'Medium', status:'Verified', ownerId:'USR-DEV', dueDate:'2026-08-20', evidence:'Stack details appeared in application log.', remediation:'Centralized sanitized exception handler.', createdAt:D(16), updatedAt:D(21) }
    ],
    automationRuns: [
      { id:'AUTO-PLAY-2201', projectId:'PRJ-COMMERCE', tool:'Playwright', suite:'Checkout E2E', pipeline:'GitHub Actions / release-1.2', status:'Failed', total:86, passed:78, failed:8, durationSeconds:742, branch:'release/1.2', commit:'a91c4d2', startedAt:D(22,'06:40:00'), createdAt:D(22,'06:40:00'), updatedAt:D(22,'06:53:00') },
      { id:'AUTO-K6-2198', projectId:'PRJ-COMMERCE', tool:'k6', suite:'Checkout Load', pipeline:'Jenkins / perf-stage', status:'Passed', total:12, passed:12, failed:0, durationSeconds:1800, branch:'release/1.2', commit:'8bf11ae', startedAt:D(21,'18:00:00'), createdAt:D(21,'18:00:00'), updatedAt:D(21,'18:30:00') },
      { id:'AUTO-ZAP-2190', projectId:'PRJ-COMMERCE', tool:'OWASP ZAP', suite:'Staging Baseline', pipeline:'GitLab CI / dast', status:'Warning', total:31, passed:28, failed:3, durationSeconds:965, branch:'main', commit:'19fa4e0', startedAt:D(21,'02:00:00'), createdAt:D(21,'02:00:00'), updatedAt:D(21,'02:17:00') }
    ],
    environments: [
      { id:'ENV-COM-DEV', projectId:'PRJ-COMMERCE', name:'Development', type:'Development', url:'https://dev.example.com', version:'1.3.0-dev.18', health:'Healthy', region:'us-east-1', lastDeployment:D(22,'09:15:00'), configuration:'Docker / Kubernetes', createdAt:D(5), updatedAt:D(22) },
      { id:'ENV-COM-STG', projectId:'PRJ-COMMERCE', name:'Staging', type:'Staging', url:'https://staging.example.com', version:'1.2.0-rc.4', health:'Degraded', region:'us-east-1', lastDeployment:D(22,'06:15:00'), configuration:'Kubernetes / PostgreSQL / Redis', createdAt:D(5), updatedAt:D(22) },
      { id:'ENV-COM-PRD', projectId:'PRJ-COMMERCE', name:'Production', type:'Production', url:'https://example.com', version:'1.1.7', health:'Healthy', region:'multi-region', lastDeployment:D(18,'10:30:00'), configuration:'Kubernetes / PostgreSQL HA / CDN', createdAt:D(5), updatedAt:D(22) },
      { id:'ENV-ERP-UAT', projectId:'PRJ-ERP', name:'ERP UAT', type:'UAT', url:'', version:'2026.08.21.3', health:'Healthy', region:'us-central', lastDeployment:D(21,'06:30:00'), configuration:'VM cluster / SQL Server', createdAt:D(7), updatedAt:D(21) }
    ],
    releases: [
      { id:'REL-COM-1.2', projectId:'PRJ-COMMERCE', name:'Commerce 1.2', version:'1.2.0', status:'Testing', targetDate:'2026-08-29', build:'1.2.0-rc.4', ownerId:'USR-ADMIN', qualityGate:'Blocked', readiness:76, notes:'Checkout modernization and accessibility improvements.', createdAt:D(12), updatedAt:D(22) },
      { id:'REL-ERP-2026.9', projectId:'PRJ-ERP', name:'ERP September Release', version:'2026.9', status:'UAT', targetDate:'2026-09-12', build:'2026.08.21.3', ownerId:'USR-QA', qualityGate:'Conditional', readiness:64, notes:'Journal approval modernization.', createdAt:D(10), updatedAt:D(21) }
    ],
    qualityAudits: [
      { id:'AUD-COM-014', projectId:'PRJ-COMMERCE', type:'Release Quality Gate', title:'Commerce 1.2 readiness review', standard:'Internal QMS / OWASP ASVS', status:'Open', score:76, findings:5, ownerId:'USR-ADMIN', dueDate:'2026-08-27', summary:'Blocked by critical defect and two high security findings.', createdAt:D(21), updatedAt:D(22) },
      { id:'AUD-ERP-009', projectId:'PRJ-ERP', type:'Process Audit', title:'ERP UAT evidence audit', standard:'ISO 9001-oriented QMS', status:'Passed', score:92, findings:1, ownerId:'USR-QA', dueDate:'2026-08-22', summary:'Evidence quality is strong; one naming inconsistency noted.', createdAt:D(19), updatedAt:D(22) }
    ],
    documents: [
      { id:'DOC-COM-SRS', projectId:'PRJ-COMMERCE', type:'SRS', title:'Commerce 1.2 Software Requirements', version:'2.3', status:'Approved', ownerId:'USR-QA', updatedAt:D(20), createdAt:D(6), content:'Requirements baseline for Commerce 1.2.' },
      { id:'DOC-COM-STR', projectId:'PRJ-COMMERCE', type:'Test Strategy', title:'Commerce Quality Strategy', version:'1.4', status:'Approved', ownerId:'USR-ADMIN', updatedAt:D(21), createdAt:D(8), content:'Risk-based multi-layer testing strategy.' },
      { id:'DOC-ERP-UAT', projectId:'PRJ-ERP', type:'Test Plan', title:'ERP UAT Plan', version:'1.1', status:'In Review', ownerId:'USR-QA', updatedAt:D(21), createdAt:D(14), content:'UAT scope, entry/exit criteria and responsibilities.' }
    ],
    tools: [
      { id:'TOOL-PLAY', category:'Web Automation', name:'Playwright', status:'Connected', integrationType:'CLI / JSON', lastRun:D(22,'06:40:00'), description:'Cross-browser end-to-end test execution.' },
      { id:'TOOL-SEL', category:'Web Automation', name:'Selenium', status:'Available', integrationType:'JUnit / TestNG', lastRun:'', description:'WebDriver automation adapter.' },
      { id:'TOOL-POST', category:'API Testing', name:'Postman / Newman', status:'Connected', integrationType:'Newman JSON', lastRun:D(21,'15:10:00'), description:'API collection execution and result import.' },
      { id:'TOOL-APP', category:'Mobile', name:'Appium', status:'Available', integrationType:'JUnit / Mocha', lastRun:'', description:'Android and iOS automation adapter.' },
      { id:'TOOL-K6', category:'Performance', name:'k6', status:'Connected', integrationType:'JSON summary', lastRun:D(21,'18:00:00'), description:'Load and performance test result ingestion.' },
      { id:'TOOL-JMET', category:'Performance', name:'JMeter', status:'Available', integrationType:'JTL', lastRun:'', description:'JMeter result importer.' },
      { id:'TOOL-ZAP', category:'Security', name:'OWASP ZAP', status:'Connected', integrationType:'JSON / XML', lastRun:D(21,'02:00:00'), description:'DAST baseline and full scan result ingestion.' },
      { id:'TOOL-SONAR', category:'Code Quality', name:'SonarQube', status:'Available', integrationType:'Webhook / API', lastRun:'', description:'Code quality and SAST gate adapter.' },
      { id:'TOOL-TRIVY', category:'Security', name:'Trivy', status:'Available', integrationType:'SARIF / JSON', lastRun:'', description:'Container, IaC and dependency scan importer.' },
      { id:'TOOL-GHA', category:'CI/CD', name:'GitHub Actions', status:'Connected', integrationType:'Webhook', lastRun:D(22,'06:40:00'), description:'Pipeline event and artifact integration.' },
      { id:'TOOL-JENK', category:'CI/CD', name:'Jenkins', status:'Connected', integrationType:'Webhook / JUnit', lastRun:D(21,'18:00:00'), description:'Build, deployment and test result ingestion.' },
      { id:'TOOL-CYP', category:'Web Automation', name:'Cypress', status:'Available', integrationType:'Mocha / JUnit', lastRun:'', description:'Cypress result adapter.' }
    ],
    activities: [
      { id:'ACT-001', actorId:'USR-QA', action:'created', entity:'Defect', entityId:'BUG-COM-417', message:'Reported critical duplicate-order defect', createdAt:D(22,'08:20:00') },
      { id:'ACT-002', actorId:'USR-SEC', action:'updated', entity:'Vulnerability', entityId:'VULN-COM-068', message:'Assigned API rate-limit finding for remediation', createdAt:D(22,'09:05:00') },
      { id:'ACT-003', actorId:'USR-DEV', action:'deployed', entity:'Environment', entityId:'ENV-COM-STG', message:'Deployed build 1.2.0-rc.4 to Staging', createdAt:D(22,'06:15:00') },
      { id:'ACT-004', actorId:'USR-QA', action:'executed', entity:'Test Run', entityId:'RUN-COM-0822', message:'Started Release 1.2 regression run', createdAt:D(22,'07:30:00') },
      { id:'ACT-005', actorId:'USR-ADMIN', action:'reviewed', entity:'Quality Audit', entityId:'AUD-COM-014', message:'Quality gate remains blocked at 76%', createdAt:D(22,'11:20:00') }
    ]
  };
}
